version: "3.4"
services:
  web:
    image: lie6055/project_api:22
    ports:
      - "5000:5000"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      -webnet
networks:
  webnet:
